#!/usr/bin/env python3
"""Train grouped out-of-fold linear arc-potential rankers.

The label is the future-leaked dominance oracle produced on *training*
states.  Every reported prediction is generated by a model that did not see
the target state's trace, routes, timings, or outcomes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import statistics
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from lunar_ice_bpc.exact.core.data import load_lunar_ice_data  # noqa: E402
from lunar_ice_bpc.guidance.proof_queue_potential_features import (  # noqa: E402
    PROOF_QUEUE_ARC_FEATURE_SCHEMA_V1,
    build_proof_queue_arc_features,
)


SCHEMA = "lunar_ice_bpc.p0v3_proof_queue_arc_linear_grouped_cv.v1"
POTENTIAL_SCHEMA = "lunar_ice_bpc.p0v3_proof_queue_potential.v1"
ALPHAS = (0.001, 0.01, 0.1, 1.0, 10.0)


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
        + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def _instance_index(roots: tuple[Path, ...]) -> dict[str, Path]:
    index: dict[str, Path] = {}
    for root in roots:
        for path in root.rglob("*_logical_graph.json"):
            payload = _load(path)
            instance_id = str(payload.get("instance_id") or "")
            if not instance_id:
                continue
            if instance_id in index:
                raise SystemExit(f"duplicate instance id {instance_id}")
            index[instance_id] = path.resolve()
    return index


def _folds(examples: list[dict], fold_count: int) -> dict[str, int]:
    by_scale: dict[int, list[dict]] = {}
    for example in examples:
        by_scale.setdefault(int(example["scale"]), []).append(example)
    assignment = {}
    for scale, rows in by_scale.items():
        rows.sort(key=lambda row: str(row["instance_content_hash"]))
        for index, row in enumerate(rows):
            assignment[str(row["source_state_hash"])] = (
                index % int(fold_count)
            )
    return assignment


def _weighted_stats(examples: list[dict]) -> tuple[np.ndarray, np.ndarray]:
    feature_count = int(examples[0]["x"].shape[1])
    mean = np.zeros(feature_count, dtype=np.float64)
    total = 0.0
    for example in examples:
        x = example["x"][example["observed"]]
        weight = 1.0 / max(1, x.shape[0])
        mean += weight * x.sum(axis=0)
        total += weight * x.shape[0]
    mean /= max(1.0e-12, total)
    variance = np.zeros(feature_count, dtype=np.float64)
    for example in examples:
        x = example["x"][example["observed"]]
        weight = 1.0 / max(1, x.shape[0])
        variance += weight * ((x - mean) ** 2).sum(axis=0)
    variance /= max(1.0e-12, total)
    std = np.sqrt(variance)
    std[std < 1.0e-8] = 1.0
    return mean, std


def _fit(
    examples: list[dict],
    alpha: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    mean, std = _weighted_stats(examples)
    feature_count = int(mean.shape[0])
    gram = np.zeros((feature_count + 1, feature_count + 1))
    rhs = np.zeros(feature_count + 1)
    for example in examples:
        mask = example["observed"]
        x = (example["x"][mask] - mean) / std
        x = np.column_stack((x, np.ones(x.shape[0])))
        y = example["target"][mask]
        weight = 1.0 / max(1, x.shape[0])
        gram += weight * (x.T @ x)
        rhs += weight * (x.T @ y)
    penalty = np.eye(feature_count + 1) * float(alpha)
    penalty[-1, -1] = 0.0
    coefficient = np.linalg.solve(gram + penalty, rhs)
    return coefficient, mean, std


def _predict(
    example: dict,
    model: tuple[np.ndarray, np.ndarray, np.ndarray],
) -> np.ndarray:
    coefficient, mean, std = model
    x = (example["x"] - mean) / std
    return x @ coefficient[:-1] + coefficient[-1]


def _ranks(values: np.ndarray) -> np.ndarray:
    order = np.argsort(values, kind="mergesort")
    ranks = np.empty(values.shape[0], dtype=np.float64)
    start = 0
    while start < order.shape[0]:
        end = start + 1
        while (
            end < order.shape[0]
            and values[order[end]] == values[order[start]]
        ):
            end += 1
        rank = 0.5 * (start + end - 1)
        ranks[order[start:end]] = rank
        start = end
    return ranks


def _correlation(left: np.ndarray, right: np.ndarray) -> float:
    left = left - left.mean()
    right = right - right.mean()
    denominator = math.sqrt(
        float(left @ left) * float(right @ right)
    )
    return 0.0 if denominator <= 1.0e-12 else float(left @ right) / denominator


def _metrics(example: dict, prediction: np.ndarray) -> dict:
    mask = example["observed"]
    target = example["target"][mask]
    predicted = prediction[mask]
    positive_count = max(1, int((target > 0.0).sum()))
    k = min(positive_count, target.shape[0])
    target_top = set(np.argsort(target)[-k:].tolist())
    predicted_top = set(np.argsort(predicted)[-k:].tolist())
    return {
        "observed_arc_count": int(target.shape[0]),
        "positive_target_arc_count": int((target > 0.0).sum()),
        "pearson": _correlation(target, predicted),
        "spearman": _correlation(_ranks(target), _ranks(predicted)),
        "top_target_count_recall": (
            len(target_top & predicted_top) / max(1, len(target_top))
        ),
        "random_top_recall": k / max(1, target.shape[0]),
        "mse": float(np.mean((target - predicted) ** 2)),
    }


def _choose_alpha(training: list[dict]) -> tuple[float, dict]:
    if len(training) < 4:
        return 0.1, {"selection": "fixed_small_sample", "alpha": 0.1}
    scores = {}
    ordered = sorted(training, key=lambda row: row["source_state_hash"])
    for alpha in ALPHAS:
        fold_scores = []
        for index, heldout in enumerate(ordered):
            inner = [
                row for inner_index, row in enumerate(ordered)
                if inner_index != index
            ]
            prediction = _predict(heldout, _fit(inner, alpha))
            fold_scores.append(_metrics(heldout, prediction)["spearman"])
        scores[str(alpha)] = statistics.fmean(fold_scores)
    selected = max(ALPHAS, key=lambda value: (scores[str(value)], -value))
    return selected, {
        "selection": "leave_one_state_out_training_only_spearman",
        "scores": scores,
        "alpha": selected,
    }


def _normalize_potential(values: np.ndarray) -> np.ndarray:
    centered = values - values.mean()
    maximum = max(1.0e-12, float(np.abs(centered).max()))
    return centered / maximum


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--oracle-summary", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--fold-count", type=int, default=5)
    parser.add_argument("--instance-root", action="append", required=True)
    args = parser.parse_args()

    oracle_path = (ROOT / args.oracle_summary).resolve()
    output_dir = (ROOT / args.output_dir).resolve()
    output_path = (ROOT / args.output).resolve()
    roots = tuple((ROOT / value).resolve() for value in args.instance_root)
    index = _instance_index(roots)
    oracle = _load(oracle_path)
    unique_records = {}
    for record in oracle.get("records") or ():
        unique_records.setdefault(
            str(record["source_state_hash"]),
            dict(record),
        )
    examples = []
    feature_names = None
    for record in unique_records.values():
        instance_id = str(record["instance_id"])
        instance_path = index.get(instance_id)
        if instance_path is None:
            raise SystemExit(f"missing instance {instance_id}")
        data = load_lunar_ice_data(_load(instance_path))
        control = _load(Path(record["paths"]["qc0"]))
        snapshot = _load(Path(control["source_snapshot_path"]))
        features = build_proof_queue_arc_features(data, snapshot)
        potential = _load(Path(record["potential_path"]))
        if feature_names is None:
            feature_names = features.feature_names
        elif feature_names != features.feature_names:
            raise SystemExit("feature schema drift")
        target_by_arc = {
            str(key): float(value)
            for key, value in potential["arc_potentials"].items()
        }
        trace_rows = list(
            control["proof_telemetry"]["proof_queue_arc_potential_trace"]
        )
        observed_by_arc = {}
        for row in trace_rows:
            from lunar_ice_bpc.exact.bpc.guidance.contracts import (
                canonical_arc_candidate_id,
            )

            arc_id = canonical_arc_candidate_id(
                row["source"], row["target"], row["path_type"]
            )
            observed_by_arc[arc_id] = (
                int(row.get("incoming_evaluated") or 0) > 0
            )
        if set(target_by_arc) != set(features.arc_candidate_ids):
            raise SystemExit("target/feature arc universe mismatch")
        examples.append(
            {
                "instance_id": instance_id,
                "instance_content_hash": data.instance_content_hash,
                "source_state_hash": str(record["source_state_hash"]),
                "scale": int(record["scale"]),
                "instance_path": str(instance_path),
                "snapshot_path": str(
                    Path(control["source_snapshot_path"]).resolve()
                ),
                "arc_ids": features.arc_candidate_ids,
                "x": np.asarray(features.rows, dtype=np.float64),
                "target": np.asarray(
                    [target_by_arc[arc_id] for arc_id in features.arc_candidate_ids],
                    dtype=np.float64,
                ),
                "observed": np.asarray(
                    [
                        observed_by_arc.get(arc_id, False)
                        for arc_id in features.arc_candidate_ids
                    ],
                    dtype=bool,
                ),
            }
        )
    fold_count = max(2, min(int(args.fold_count), len(examples)))
    assignment = _folds(examples, fold_count)
    rows = []
    fold_models = []
    for fold in range(fold_count):
        validation = [
            row for row in examples
            if assignment[row["source_state_hash"]] == fold
        ]
        training = [
            row for row in examples
            if assignment[row["source_state_hash"]] != fold
        ]
        alpha, selection = _choose_alpha(training)
        model = _fit(training, alpha)
        coefficient, mean, std = model
        fold_models.append(
            {
                "fold": fold,
                "alpha_selection": selection,
                "training_state_hashes": sorted(
                    row["source_state_hash"] for row in training
                ),
                "validation_state_hashes": sorted(
                    row["source_state_hash"] for row in validation
                ),
                "coefficient": coefficient.tolist(),
                "feature_mean": mean.tolist(),
                "feature_std": std.tolist(),
            }
        )
        for example in validation:
            prediction = _predict(example, model)
            normalized = _normalize_potential(prediction)
            metrics = _metrics(example, normalized)
            identity = {
                "fold": fold,
                "source_state_hash": example["source_state_hash"],
                "training_state_hashes": fold_models[-1][
                    "training_state_hashes"
                ],
                "arc_potentials": {
                    arc_id: round(float(value), 12)
                    for arc_id, value in zip(
                        example["arc_ids"], normalized
                    )
                },
            }
            potential_id = hashlib.sha256(
                json.dumps(
                    identity,
                    sort_keys=True,
                    separators=(",", ":"),
                ).encode("utf-8")
            ).hexdigest()
            potential_path = (
                output_dir
                / f"{example['scale']}_{example['source_state_hash'][:16]}"
                / "linear_oof_potential.json"
            )
            potential_payload = {
                "schema_version": POTENTIAL_SCHEMA,
                "development_only": True,
                "deployable": False,
                "ordering_only": True,
                "can_filter": False,
                "can_prune": False,
                "can_change_reduced_cost": False,
                "can_certify": False,
                "future_leakage": False,
                "valid_use": "grouped_cv_realizability_only",
                "source_kind": "grouped_cv_out_of_fold_linear",
                "instance_content_hash": example[
                    "instance_content_hash"
                ],
                "source_state_hash": example["source_state_hash"],
                "method": "ridge_regression_arc_dominance_ranker",
                "sign": "learned_target",
                "feature_schema_version": (
                    PROOF_QUEUE_ARC_FEATURE_SCHEMA_V1
                ),
                "normalization_version": "centered_maxabs.v1",
                "ood_policy_version": "grouped_cv_exact_state.v1",
                "potential_id": potential_id,
                "task_potentials": {},
                "arc_potentials": identity["arc_potentials"],
                "audit": {
                    "fold": fold,
                    "target_state_excluded_from_training": True,
                    "training_state_count": len(training),
                    **metrics,
                },
            }
            _write(potential_path, potential_payload)
            rows.append(
                {
                    "fold": fold,
                    "instance_id": example["instance_id"],
                    "instance_content_hash": example[
                        "instance_content_hash"
                    ],
                    "source_state_hash": example["source_state_hash"],
                    "scale": example["scale"],
                    "instance_path": example["instance_path"],
                    "snapshot_path": example["snapshot_path"],
                    "potential_path": str(potential_path),
                    **metrics,
                }
            )
    by_scale = {}
    for scale in sorted({int(row["scale"]) for row in rows}):
        selected = [row for row in rows if int(row["scale"]) == scale]
        by_scale[str(scale)] = {
            "state_count": len(selected),
            "mean_spearman": statistics.fmean(
                row["spearman"] for row in selected
            ),
            "median_spearman": statistics.median(
                row["spearman"] for row in selected
            ),
            "mean_top_target_count_recall": statistics.fmean(
                row["top_target_count_recall"] for row in selected
            ),
            "mean_random_top_recall": statistics.fmean(
                row["random_top_recall"] for row in selected
            ),
        }
    payload = {
        "schema_version": SCHEMA,
        "development_only": True,
        "deployable": False,
        "source_oracle_summary": str(oracle_path),
        "feature_schema_version": PROOF_QUEUE_ARC_FEATURE_SCHEMA_V1,
        "feature_names": list(feature_names or ()),
        "fold_count": fold_count,
        "split_unit": "instance_content_hash",
        "normalization_fit_on_training_only": True,
        "target_state_trace_excluded_from_training": True,
        "rows": rows,
        "fold_models": fold_models,
        "aggregate_by_scale": by_scale,
        "gate": {
            "permits_gat_training": False,
            "permits_online_deployment": False,
            "reason": (
                "out-of-fold exact queue replay must show net benefit before "
                "any larger model is trained"
            ),
        },
    }
    _write(output_path, payload)
    print(json.dumps(by_scale, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
