"""Frozen identities for the binding-V2 GAT experiment line."""

P0V2_EXPERIMENT_CONTROL_ID = (
    "FROZEN_NATIVE_LIVE_SRI_P0_OPTIMIZED_BASELINE_V2"
)
P0V2_BINDING_V2_B0_CONTROL_ID = (
    "P0V2_BINDING_V2_SAME_CODE_B0_CONTROL_20260723"
)
GAT_EXPERIMENT_FAMILY_ID = "P0V2_CROSS_SCALE_GAT_ORDERING_V1"
PRODUCTION_DEFAULT_LIVE_SRI_POLICY = "no_cut"
EXPERIMENT_LIVE_SRI_POLICY = "P0"

