"""Pricing backend registry for exact-safe SPPRC execution."""

from lunar_ice_bpc.exact.bpc.pricing.backends.base import (
    BACKEND_MODE_EXACT_PROOF,
    BACKEND_MODE_NEGATIVE_HARVEST,
    BACKEND_OBJECTIVE_OFFICIAL,
    BACKEND_OBJECTIVE_PHASE_ONE,
    PRICING_LIFECYCLE_SCOPES,
    PRICING_LIFECYCLE_SCOPE_ROOT_CG,
    PRICING_LIFECYCLE_SCOPE_TREE_NODE,
    PRICING_LIFECYCLE_SCOPE_UNSPECIFIED,
    PROOF_QUEUE_POLICIES,
    PROOF_QUEUE_POLICY_Q0,
    PROOF_QUEUE_POLICY_QC0,
    PROOF_QUEUE_POLICY_QB1,
    PROOF_QUEUE_POLICY_QD1,
    PROOF_QUEUE_POLICY_QG1,
    BackendPricingRequest,
    BackendResult,
    PricingBackend,
)
from lunar_ice_bpc.exact.bpc.pricing.backends.native_rcspp import (
    NATIVE_DSSR_HOST_BACKEND_ID,
    NATIVE_DSSR_INPROCESS_BACKEND_ID,
    NATIVE_DSSR_V2_HOST_BACKEND_ID,
    NATIVE_DSSR_V2_INPROCESS_BACKEND_ID,
    NATIVE_HOST_BACKEND_ID,
    NATIVE_INPROCESS_BACKEND_ID,
    NATIVE_NG_DSSR_V3_HOST_BACKEND_ID,
    NATIVE_NG_DSSR_V3_INPROCESS_BACKEND_ID,
    NativeDssrHostBackend,
    NativeDssrInprocessBackend,
    NativeDssrV2HostBackend,
    NativeDssrV2InprocessBackend,
    NativeNgDssrV3HostBackend,
    NativeNgDssrV3InprocessBackend,
    NativeRcsppHostBackend,
    NativeRcsppInprocessBackend,
)
from lunar_ice_bpc.exact.bpc.pricing.backends.native_bidirectional_hybrid import (
    NATIVE_BIDIRECTIONAL_MIDPOINT_HYBRID_BACKEND_ID,
    NATIVE_BIDIRECTIONAL_MIDPOINT_PARTIAL_HYBRID_BACKEND_ID,
    NATIVE_BIDIRECTIONAL_ROOT_PARTIAL_HYBRID_BACKEND_ID,
    NativeBidirectionalMidpointHybridBackend,
    NativeBidirectionalMidpointPartialHybridBackend,
    NativeBidirectionalRootPartialHybridBackend,
)
from lunar_ice_bpc.exact.bpc.pricing.backends.python_reference import (
    PYTHON_REFERENCE_BACKEND_ID,
    PythonReferenceBackend,
)
from lunar_ice_bpc.exact.bpc.pricing.backends.registry import BackendRegistry
from lunar_ice_bpc.exact.bpc.pricing.backends.scale_profiles import (
    DEFAULT_NATIVE_SPPRC_SCALE_PROFILES,
    NativeSpprcScaleProfile,
    native_spprc_scale_profile,
)

__all__ = [
    "BACKEND_MODE_EXACT_PROOF",
    "BACKEND_MODE_NEGATIVE_HARVEST",
    "BACKEND_OBJECTIVE_OFFICIAL",
    "BACKEND_OBJECTIVE_PHASE_ONE",
    "PRICING_LIFECYCLE_SCOPES",
    "PRICING_LIFECYCLE_SCOPE_ROOT_CG",
    "PRICING_LIFECYCLE_SCOPE_TREE_NODE",
    "PRICING_LIFECYCLE_SCOPE_UNSPECIFIED",
    "PROOF_QUEUE_POLICIES",
    "PROOF_QUEUE_POLICY_Q0",
    "PROOF_QUEUE_POLICY_QC0",
    "PROOF_QUEUE_POLICY_QB1",
    "PROOF_QUEUE_POLICY_QD1",
    "PROOF_QUEUE_POLICY_QG1",
    "BackendPricingRequest",
    "BackendRegistry",
    "BackendResult",
    "DEFAULT_NATIVE_SPPRC_SCALE_PROFILES",
    "NATIVE_DSSR_HOST_BACKEND_ID",
    "NATIVE_DSSR_INPROCESS_BACKEND_ID",
    "NATIVE_DSSR_V2_HOST_BACKEND_ID",
    "NATIVE_DSSR_V2_INPROCESS_BACKEND_ID",
    "NATIVE_HOST_BACKEND_ID",
    "NATIVE_INPROCESS_BACKEND_ID",
    "NATIVE_NG_DSSR_V3_HOST_BACKEND_ID",
    "NATIVE_NG_DSSR_V3_INPROCESS_BACKEND_ID",
    "NATIVE_BIDIRECTIONAL_MIDPOINT_HYBRID_BACKEND_ID",
    "NATIVE_BIDIRECTIONAL_MIDPOINT_PARTIAL_HYBRID_BACKEND_ID",
    "NATIVE_BIDIRECTIONAL_ROOT_PARTIAL_HYBRID_BACKEND_ID",
    "NativeDssrHostBackend",
    "NativeDssrInprocessBackend",
    "NativeDssrV2HostBackend",
    "NativeDssrV2InprocessBackend",
    "NativeNgDssrV3HostBackend",
    "NativeNgDssrV3InprocessBackend",
    "NativeRcsppHostBackend",
    "NativeRcsppInprocessBackend",
    "NativeBidirectionalMidpointHybridBackend",
    "NativeBidirectionalMidpointPartialHybridBackend",
    "NativeBidirectionalRootPartialHybridBackend",
    "NativeSpprcScaleProfile",
    "PYTHON_REFERENCE_BACKEND_ID",
    "PricingBackend",
    "PythonReferenceBackend",
    "native_spprc_scale_profile",
]
